workflows:
  empty:
    name: Empty
    environment:
      xcode: 12.5
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v+([0-9]).+([0-9]).+([0-9])"
    scripts:
      - echo tag build

