workflows:
  build:
    instance_type: linux
    name: Tag build
    environment:
      vars:
        CM_CLONE_DEPTH: 42
    triggering:
      events:
        - tag
        - push
    scripts:
      - echo "Tag build"

