workflows:
  keystores:
    name: Keystores
    environment:
      android_signing:
        - keystore: artemiis-keystore
          keystore_environment_variable: THIS_KEYSTORE_PATH_ON_DISK_1
          keystore_password_environment_variable: THIS_KEYSTORE_PASSWORD_1
          key_alias_environment_variable: THIS_KEY_ALIAS_1
          key_password_environment_variable: THIS_KEY_PASSWORD_1
    scripts:
      - echo "Keystores"
    