workflows:
  build:
    name: Build
    environment:
      vars:
        ALLOW_DRAFT_PR: true
    triggering:
      events:
        - pull_request
    when:
      changeset:
        includes:
          - foobar.txt
    scripts:
      - echo "Build vi"

