workflows:
  build:
    name: Triggering requires build inputs with defaults
    inputs:
      test_no_default:
        description: Test no default
        type: string
    triggering:
      events:
        - push
    scripts:
      - echo "Triggering requires build inputs with defaults
