workflows:
  build:
    name: Build
    instance_type: mac_mini_m1
    max_build_duration: 3
    triggering:
      events:
        - pull_request
    scripts:
      - echo "Check if merges for PR (with depth 1 on staging!)"

