workflows:
  build:
    name: Placeholder build inputs
    inputs:
        site:
            description: Which website should we deploy?
            type: choice
            options:
                - codemagic
                - flutterci
                - reactnativeci
                - unitycicd
    labels:
      - ${{ inputs.wrong }}
    scripts:
      - echo "Placeholder build inputs"
