workflows:
  empty:
    name: Empty
    environment:
      vars:
        $MY_VAR: foo
      xcode: 12.3
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v+([0-9]).+([0-9]).+([0-9])"
    scripts:
      - echo tag build
