workflows:
  build:
    name: Google Play
    environment:
      groups: 
        - google-play
    scripts:
      - echo "Google Play publishing"
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

