workflows:
  build:
    name: Build
    environment:
      vars:
        ALLOW_DRAFT_PR: true
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - echo "Build CM"
      - name: Build
        script: echo "Build"

